### ISSUE TITLE
Missing character information in LogMatchEnd telemetry

### ISSUE THREAD

**Issue by sebastian-raubach** [GPLNature/pubgapi#12]
When fetching the character information of the `LogMatchEnd` telemetry event, I get a list of all characters, but all of their fields are `null`.

Telemetry URL: `https://telemetry-cdn.pubg.com/bluehole-pubg/console/2024/07/31/15/34/701361e0-4f52-11ef-aa99-e22c486eb3a4-telemetry.json`

**Comment by GPLNature** [comment]
Sorry for the late reply
I'll check the issue, but it may take time for me to find the exact issue.

**Comment by GPLNature** [comment]
I checked the telemetry url you given.
The real data exists, but when get the data through the code, the real data disappeared as you said.

I can't fix it right now, because I don't know where is that problems produce.

it could be json dependency we use, Gson library.
I'll test another json library like Jackson.

**Comment by GPLNature** [comment]
Currently Working on Convert JsonLibrary Gson to Jackson.

**Comment by GPLNature** [comment]
Fix the issue.
I'll publish to maven repo in this week

**Comment by GPLNature** [comment]
sorry for too late to publish new versions.

I just published, version 0.2.0, you could use version 0.2.0.
thanks.
